"use client";
import {FormEvent,useEffect,useState} from "react";

type Permission={code:string;name:string;description?:string};
export default function UsuariosPage(){
 const [rows,setRows]=useState<any[]>([]),[catalog,setCatalog]=useState<Permission[]>([]),[msg,setMsg]=useState(""),[form,setForm]=useState({email:"",password:"",permissions:["LICENSES"] as string[]}),[editing,setEditing]=useState<Record<number,string[]>>({});
 async function load(){const r=await fetch("/api/admin/users");if(r.ok){const b=await r.json();setRows(b.users||[]);setCatalog(b.permissionCatalog||[]);setEditing(Object.fromEntries((b.users||[]).map((u:any)=>[u.id,u.permissions||[]])));}else setMsg("No autorizado.");}
 useEffect(()=>{load()},[]);
 function togglePermission(list:string[],code:string){return list.includes(code)?list.filter(x=>x!==code):[...list,code];}
 async function create(e:FormEvent){e.preventDefault();setMsg("");const r=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const b=await r.json().catch(()=>({}));if(!r.ok){setMsg(b.error||"No se pudo crear");return;}setForm({email:"",password:"",permissions:["LICENSES"]});setMsg("Usuario creado correctamente.");await load();}
 async function toggle(id:number,active:boolean){const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,active:!active})});const b=await r.json().catch(()=>({}));setMsg(r.ok?(active?"Usuario desactivado.":"Usuario activado."):b.error||"No se pudo actualizar");if(r.ok)load();}
 async function reset(id:number){const pwd=prompt("Ingresá una nueva contraseña temporal (mínimo 8 caracteres):");if(!pwd)return;const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,password:pwd})});const b=await r.json().catch(()=>({}));setMsg(r.ok?"Contraseña restablecida.":b.error||"No se pudo restablecer");}
 async function savePermissions(id:number){const permissions=editing[id]||[];const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,permissions})});const b=await r.json().catch(()=>({}));setMsg(r.ok?"Permisos actualizados. Los cambios se aplican inmediatamente.":b.error||"No se pudieron actualizar los permisos");if(r.ok)load();}
 return <div className="stack"><div><h1 className="heading">Usuarios y permisos</h1><p className="subheading">Cada usuario puede tener uno o varios permisos operativos. Podremos agregar nuevos tipos de permiso sin cambiar este esquema.</p></div>
 <form className="card stack" onSubmit={create}><h2 style={{margin:0}}>Nuevo usuario</h2><div className="form-row"><div><label className="label">Correo</label><input className="input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><label className="label">Contraseña inicial</label><input className="input" type="password" minLength={8} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div></div>
 <div><label className="label">Permisos</label><div className="stack" style={{gap:8}}>{catalog.map(p=><label key={p.code} className="notice info" style={{display:"flex",gap:10,alignItems:"flex-start",cursor:"pointer"}}><input type="checkbox" checked={form.permissions.includes(p.code)} onChange={()=>setForm({...form,permissions:togglePermission(form.permissions,p.code)})}/><span><strong>{p.name}</strong>{p.description&&<><br/><span>{p.description}</span></>}</span></label>)}</div></div>
 <div className="notice info">Ejemplo: un mismo usuario puede tener simultáneamente <strong>Operador de Licencias</strong> y <strong>Operador de Asistencia</strong>.</div>{msg&&<div className="notice info">{msg}</div>}<button className="btn btn-primary">Crear usuario</button></form>
 <div className="card table-wrap"><table><thead><tr><th>Correo</th><th>Permisos</th><th>Estado</th><th>Último acceso</th><th>Acciones</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.email}</td><td><div className="stack" style={{gap:6,minWidth:230}}>{catalog.map(p=><label key={p.code} style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={(editing[r.id]||[]).includes(p.code)} onChange={()=>setEditing({...editing,[r.id]:togglePermission(editing[r.id]||[],p.code)})}/><span>{p.name}</span></label>)}<button className="btn btn-secondary" onClick={()=>savePermissions(r.id)}>Guardar permisos</button></div></td><td>{r.active?"Activo":"Inactivo"}</td><td>{r.last_login_at?new Date(r.last_login_at).toLocaleString("es-AR"):"—"}</td><td><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="btn btn-secondary" onClick={()=>reset(r.id)}>Reset contraseña</button><button className="btn btn-secondary" onClick={()=>toggle(r.id,r.active)}>{r.active?"Desactivar":"Activar"}</button></div></td></tr>)}</tbody></table></div></div>;
}
